# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

pr: none
# - master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  labelBuildAndPush: Build and push

pool:
  vmImage: ubuntu-latest

stages:
- stage: check_application
  displayName: Verify lint
  jobs:
  - job: run_application
    displayName: Run application
    steps:
    # - task: DockerCompose@0
    #   inputs:
    #     containerregistrytype: 'Container Registry'
    #     dockerRegistryEndpoint: 'Azure-DockerHub'
    #     dockerComposeFile: '**/docker-compose.yaml'
    #     dockerComposeFileArgs: 'KEYCLOAK_TOKEN=123'
    #     action: 'Run a Docker Compose command'
    #     dockerComposeCommand: 'up'
    #     arguments: '-d'

    - task: CmdLine@2
      inputs:
        script: |
          cd node
          npm install
          npx eslint .


    # - task: CmdLine@2
    #   inputs:
    #     script: |
    #       docker ps
          
    #       docker image ls

    #       docker run igorcsilvaazuregithub_nodeapp npm test

    # - task: CmdLine@2
    #   inputs:
    #     script: |
    #       docker run igorcsilvaazuregithub_nodeapp npx eslint app.js

- stage: buildAndPush
  displayName: $(labelBuildAndPush) the image
  jobs:
  - job: buildAndPush
    displayName: $(labelBuildAndPush)
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Azure-DockerHub'
        repository: 'igoru23/azure-github'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/node/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/node'
        tags: |
          $(tag)
          latest