# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  labelBuildAndPush: Build and push

stages:
- stage: test
  displayName: Test the application
  jobs:
  - job: test
    displayName: Test application
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Azure-DockerHub'
        dockerComposeFile: '**/docker-compose.yml'
        dockerComposeFileArgs: 'KEYCLOAK_TOKEN=123'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up'
        arguments: '-d'
    
    - task: CmdLine@2
      inputs:
        script: |
          docker ps
          
          docker image ls

# - stage: buildAndPush
#   displayName: $(labelBuildAndPush) the image
#   jobs:
#   - job: buildAndPush
#     displayName: $(labelBuildAndPush)
#     pool:
#       vmImage: ubuntu-latest
#     steps:

#     - task: Docker@2
#       inputs:
#         containerRegistry: 'Azure-DockerHub'
#         repository: 'igoru23/azure-github'
#         command: 'buildAndPush'
#         Dockerfile: '$(Build.SourcesDirectory)/node/Dockerfile'
#         buildContext: '$(Build.SourcesDirectory)/node'
#         tags: |
#           $(tag)
#           latest