# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  labelBuildAndPush: 'Build_and_push'

stages:
- stage: $(labelBuildAndPush)
  displayName: $(labelBuildAndPush) the image
  jobs:
  - job: Build_and_push
    displayName: $(labelBuildAndPush)
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/node/Dockerfile'
    #     tags: |
    #       $(tag)
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'Azure-DockerHub'
    #     repository: 'igoru23/azure-github'
    #     command: 'push'
    #     tags: |
    #       $(Build.BuildId)
    #       biruliro

    - task: Docker@2
      inputs:
        containerRegistry: 'Azure-DockerHub'
        repository: 'igoru23/azure-github'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/node/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/node'
        tags: |
          $(tag)
          latest