# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/node/Dockerfile'
    #     tags: |
    #       $(tag)

    - task: Docker@2
      inputs:
        containerRegistry: 'Azure-DockerHub'
        repository: 'igoru23/azure-github'
        command: 'buildAndPush'
        Dockerfile: './node/Dockerfile'
        buildContext: './node'