version: '3'

services:
  # Web server.
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod

    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"

  # Node app
  nodeapp:
    build:
      context: node
    container_name: nodeapp

    # Wait for the database to be ready.
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: >
      bash -c "npm install
      && node index.js"
    
    networks:
      - nodenet
    depends_on:
      - db
    volumes:
      - ./node:/usr/src/app
    tty: true

  # MySQL database.
  db:
    image: mysql:5.7
    
    # Especific command to MySQL works.
    command: --innodb-use-native-aio=0

    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    
    # Environment variables.
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

    networks: 
      - nodenet

networks:
  nodenet:
    driver: bridge