name: CI-Sonarcloud-AzurePipeline

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches: 
      - master

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # - name: Ls pwd
      #   run: |
      #     ls /home/runner/work/azure-github/azure-github

      # - run: |
      #     mkdir -p artifacts/store
      #     cp node/lcov.info artifacts/store/lcov.info

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: my-artifact
      #     path: artifacts/store/lcov.info

      # - run: ls artifacts/store 

      - name: Build the stack
        run: |
          docker-compose up -d --build
          docker exec nodeapp npm test
          
      # - name: Test app
      #   run: |
      #     docker exec nodeapp npm test

      - name: Coverage folder
        run: |
          docker exec nodeapp ls
      
      # - run: mkdir -p artifacts/

      # - name: Get coverage info
      #   run: |
      #     docker exec nodeapp ls
      #     docker cp nodeapp:/usr/src/app/coverage/lcov.info artifacts/
      
      # - name: List artifacts
      #   run: |
      #     ls artifacts/
      #     cat artifacts/lcov.info

      # - name: List artifacts 2
      #   run: ls artifacts/coverage/coverage

  # verify_code:
  #   name: Verify code security and beauty.
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #       with:
  #         fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

  #     - uses: actions/download-artifact@master
  #       with:
  #         name: my-artifact
  #         path: artifacts/store
          
  #     - run: cat artifacts/store/lcov.info

  #     - name: SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #       with:
  #         projectBaseDir: .


  # build:
  #   name: Call Azure Pipeline
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Azure Pipelines Action
  #     uses: Azure/pipelines@v1
  #     with:
  #       # Not use trailing slash.
  #       azure-devops-project-url: https://dev.azure.com/show0804/azure-github
  #       azure-pipeline-name: 'IgorCSilva.azure-github'
  #       azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
