name: CI

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches: 
      - master

jobs:
  build:
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Azure Pipelines Action
      uses: Azure/pipelines@v1
      with:
        # Not use trailing slash.
        azure-devops-project-url: https://dev.azure.com/show0804/azure-github
        azure-pipeline-name: 'IgorCSilva.azure-github'
        azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}